import type { ExpoConfig } from 'expo/config';

/**
 * All native configuration flows through this file — `ios/` is git-ignored
 * and regenerated by `npx expo prebuild`.
 *
 * Bundle IDs are locked at M0 because Apple's Family Controls distribution
 * entitlement is requested per bundle ID (see docs/APPLE_SETUP.md). The three
 * Screen Time extension targets (com.whoiam.app.ShieldConfiguration /
 * .ShieldAction / .ActivityMonitor) are added by the react-native-device-activity
 * config plugin at milestone M3.
 */
const config: ExpoConfig = {
  name: 'WHOIAM',
  slug: 'whoiam',
  version: '0.1.0',
  orientation: 'portrait',
  icon: './assets/images/icon.png',
  scheme: 'whoiam',
  userInterfaceStyle: 'automatic',
  ios: {
    bundleIdentifier: 'com.whoiam.app',
    supportsTablet: false,
  },
  android: {
    // Android ships in a later phase; package reserved now to match iOS.
    package: 'com.whoiam.app',
    adaptiveIcon: {
      backgroundColor: '#708C8E',
      foregroundImage: './assets/images/android-icon-foreground.png',
      backgroundImage: './assets/images/android-icon-background.png',
      monochromeImage: './assets/images/android-icon-monochrome.png',
    },
    predictiveBackGestureEnabled: false,
  },
  web: {
    output: 'static',
    favicon: './assets/images/favicon.png',
  },
  plugins: [
    'expo-router',
    [
      'expo-splash-screen',
      {
        backgroundColor: '#1C463E',
        image: './assets/images/splash-icon.png',
        imageWidth: 120,
      },
    ],
    'expo-sqlite',
    'expo-notifications',
  ],
  experiments: {
    typedRoutes: true,
    reactCompiler: true,
  },
};

export default config;
